### ISSUE TITLE
Comparing release version numbers is not semver compliant

### ISSUE THREAD

**Issue by arjan** [bitwalker/exrm#110]
The `get_last_release` utils function compares version numbers in a naive way:
https://github.com/bitwalker/exrm/blob/master/lib/exrm/utils.ex#L124

It should use the routines from Elixir's `Version` module.

This causes issues when generating release upgrades.

**Comment by bitwalker** [comment]
@arjan Thanks, this code predates the release of `Version`, and should have been updated, good catch!

**Comment by arjan** [comment]
The only thing is, that this will break apps that don't follow semver versioning.

**Comment by bitwalker** [comment]
I think in practice semver is pretty widely accepted as standard within the Elixir community, but it could perhaps present an issue. Maybe we can do a sanity check of the input to determine whether it matches the pattern of semver strings, and if so, use `Version`, otherwise fallback to the naive comparison. Thoughts?

**Comment by arjan** [comment]
Yeah, sounds like a sane idea. Semvers are simple, so we could do it with a regexp.

**Comment by arjan** [comment]
BTW I can do a PR if you like, got something working here already.

**Comment by bitwalker** [comment]
@arjan Sure! If you have a working solution, send me a PR and I'll review and merge ASAP

**Comment by arjan** [comment]
Wrote the code, now writing test.. :)
