### ISSUE TITLE
Hide name and cookie option from the command line

### ISSUE THREAD

**Issue by miwee** [bitwalker/exrm#114]
I'm running an exrm release on my shared host, and this is what I see in my list of processes

myserver - 34MB - 0:07:50 - 94569 - /home/myserver/webapps/portapp/dcs_backend/rel/dcs_backend/erts-6.1/bin/beam.smp -- -root /home/myserver/webapps/portapp/dcs_backend/rel/dcs_backend -progname home/myserver/webapps/portapp/dcs_backend/rel/dcs_backend/bin/dcs_backend -- -home /home/myserver -- -boot /home/myserver/webapps/portapp/dcs_backend/rel/dcs_backend/releases/0.2.0/dcs_backend -config /home/myserver/webapps/portapp/dcs_backend/rel/dcs_backend/releases/0.2.0/sys.config -pa /home/myserver/webapps/portapp/dcs_backend/rel/dcs_backend/lib/consolidated -name dcs_backend@127.0.0.1 -setcookie dcs_backend -user Elixir.IEx.CLI -extra --no-halt +iex -- console

How can I pass the name and cookie option through some other means, so that they are not visible as per part of the command line

**Comment by liveforeverx** [comment]
@miwee Do you still have a problem? (Old issue)

You need to do something like that on boot: https://github.com/travelping/enit/blob/master/src/enit_boot.erl#L39

In our old erlang release manager, we have specified it in configuration. Would be nice to have such generall feature in exrm.

**Comment by bitwalker** [comment]
@miwee @liveforeverx It looks to me like you are running the console command when starting your app, is `setcookie` and `name` being passed via flags when running `start` or `foreground`? It should be getting pulled from the `vm.args` file in those cases, but this is just off the top of my head, I can review the boot script to make sure.

**Comment by bitwalker** [comment]
ping

**Comment by liveforeverx** [comment]
@bitwalker

```
ps aux | grep beam
erts-6.3/bin/beam.smp .... -name name@127.0.0.1 -setcookie cookie -- foreground
```

It happens, because all, what specified in vm.args are passed as flags to a started beam proccess.

**Comment by bitwalker** [comment]
@liveforeverx We may be able to use `nodetool` to call the `erlang:set_cookie` function on the started node to avoid this. I'd have to test that out. Have any thoughts on that?

**Comment by liveforeverx** [comment]
@bitwalker yes, something like rpc erlang set_cookie <cookie> can work of course.

Another option, if we can it to app.script (as {apply, erlang, set_cookie, [<cookie>]} ), it would be better, as it will little bit earlier in start of a vm. Need to check, if we can easy hook functions to a script.

**Comment by bitwalker** [comment]
I think it would be pretty doable to do post-processing on the `.script` to add that in. The one issue that comes to mind is that putting it in there makes it pretty inaccessible for your average user, where `vm.args` is very user friendly. Because of the way `vm.args` is applied, we'd have to strip it from there and put it in the `.script` (this applies to the `erlang:set_cookie` option via nodetool as well actually). What feels like a good approach for making it configurable without forcing people to hand edit the `.script`? Maybe we can do some fancy shell scripting to parse out the name/cookie and feed the `vm.args` flags sans those properties, and bundle an escript which handles post-processing the `.script` file, that way users still interface with it via `vm.args`, but everything else is taken care of. The obvious downside is that this is quite complex, and may not translate easily to Windows.
