### ISSUE TITLE
config.exs not used?

### ISSUE THREAD

**Issue by eproxus** [bitwalker/exrm#139]
When reading the README, I get the impression that `config.exs` is supposed to be used to generate a `sys.config` file. However, this seems not to be the case.

Currently, a `config/config.exs` file in an umbrella project gets used when running `iex -S mix` for example, but not when running `mix release`.

**Comment by eproxus** [comment]
Perhaps this is a broader question related to #116? I.e. what configuration is used when generating which releases? More specifically, how is configuration in `project/config/` handled versus configuration in `project/apps/myapp/config` for example?

**Comment by bitwalker** [comment]
Sorry it took me so long to get back to this. This is covered to some degree in the documentation, but here's the gist:

The way umbrella projects work today, releases are built for each child application, because of this, a config file at the top level, i.e. `project/config` will never be used, instead the configuration files for each application, i.e. `project/apps/app1/config` are used. This is because exrm doesn't really distinguish between an umbrella child application and a standalone application.

I have some thoughts on providing a different approach for building releases from umbrellas, but that is how things currently work today.

**Comment by eproxus** [comment]
Ok, thanks for the explanation!
