### ISSUE TITLE
Buliding succeed but miss quite a lot of dependencies

### ISSUE THREAD

**Issue by eminarcissus** [bitwalker/exrm#141]
Hi,

I'm trying to use exrm to build the app but it failed with quite a lot of dependencies missing. So I've copied from _build/prod/* rel/project/lib/ and then try to start the app again, it says it miss dependencies of xmerl.app which is a generic erlang module I think.

I retreat back to use a old script I create to package the app with only packacking up build.sh and use erl detach to start the app which works fine.

When build the app I see quite a lot of mix error #2, don't know what does it means here, if needed I can reproduce and paste the log here, any clue what's the reason causing this?

**Comment by bitwalker** [comment]
The dependencies are missing because you likely did not add them to `applications: []` in your mix.exs. You'll need to add `:xmerl` and any other deps which are missing to `applications` then rebuild your release. As for the second part, you can ignore those errors for now (they aren't errors which apply to what exrm is doing), a fix is in the works for making the error output go away though. Can you try the above and post back with the results?
