### ISSUE TITLE
Documentation around where relx.config should go

### ISSUE THREAD

**Issue by mpahrens** [bitwalker/exrm#157]
When trying to follow the instructions as per #99 (I am compiling on ubuntu for rasp pi), I got stuck for a while trying to figure out where to put the relx.config. 

The test application in `test/fixtures/example_app` was misleading because it put it's relx.config in the root directory for the project (with mix.exs), but when I dug through the source, I see that it is actually looking for `<root>/rel/relx.config`. Which makes sense, but just as much sense as putting it in config or in the root. So I just think that it would be helpful to either change the example or update the blurb in the readme about where relx.config should go, or both :) Nice tool though! Really helpful!

**Comment by bitwalker** [comment]
Good point, just for reference, I keep an example project [exrm-test](https://github.com/bitwalker/exrm-test) up to date, that's always a good place to check rather than the test fixtures (though those *should* be accurate, if not then either it doesn't matter for some reason or the tests are out of date). The docs now have an explicit list of the possible ways to configure the release under "Release Configuration" in the documentation. Thanks!

**Comment by mpahrens** [comment]
Thank you for the speedy response! :+1:
