### ISSUE TITLE
when upgrading, if I skip a version, upgrade fails

### ISSUE THREAD

**Issue by mpahrens** [bitwalker/exrm#171]
I don't know if I am missing something here,
but I am generating releases, and in this instance, on my deployed server, I skipped a version number.

That is, for a set of my servers I upgraded them from 0.1.10 to 0.1.11 and then to 0.1.12.

On another set of servers, I tried upgrading from 0.1.10 of my app directly to 0.1.12 using:
`/path/to/my/bin/blockytalky upgrade "0.1.12"`
Where blockytalky is my app.
It tries to unpack the tarball I put in my releases/0.1.12 directory, and I get the following error:
<pre><code>
ERROR: release_handler:check_install_release failed: {no_matching_relup,
                                                      "0.1.12","0.1.10"}
</code></pre>

Do I absolutely have to upgrade to 0.1.11 in between? I don't particularly want to do a clean unpacking of my tarball if I can avoid it.

**Comment by mpahrens** [comment]
my relup for 0.1.12 looks like:
<pre><code>
{"0.1.12",
 [{"0.1.11",[],[point_of_no_return]}],
 [{"0.1.11",[],[point_of_no_return]}]}.
</code></pre>

Even though I built it with `mix release` on an environment that had my previous releases in the rel folder. I am cross compiling (like I asked about before) if that makes any difference.

**Comment by mpahrens** [comment]
this isn't a pressing issue for me (I don't need to live upgrade as these are embedded systems that go up and down constantly), so don't prioritize this for me! (and I can help investigate too!) I just wanted to know if this was intended behavior of the relup :) Good work as always.

**Comment by bitwalker** [comment]
@mpahrens Hey sorry for the delay, been spread thin across a handful of projects! In any case, what you are attempting to do here isn't supported, but that's because your release tar for 0.1.12 was built to upgrade from 0.1.11, not 0.1.10. If you wanted to build a tar to go from *.10 to *.12, you'd need to delete `rel/<app>/releases/0.1.11`, then build the release again. This time it would see it needs to upgrade from *.10 and generate the appropriate appup/relup.
