### ISSUE TITLE
Compile time configuration not populating sys.config if no conform schema definitions

### ISSUE THREAD

**Issue by mpahrens** [bitwalker/exrm#195]
So I have my phoenix application, blockytalky, and when I:
- have a configuration option in config.exs. let's say
<code><pre>
config :blockytalky, Blockytalky.Endpoint,
  check_origin:false
</pre></code>

and I compile with: `MIX_ENV=prod mix release --verbosity=verbose`

That config setting won't be in my tarred application unless I also add a conform schema for it to `blockytalky.schema.exs` and then respectively the entry for blockytalky.conf.

Is there a way to be able to add these compile time configurations and have them respected (added to the sys.config) without needing to also add them to the schema?

Or maybe I am just missing something (high probability) :)  Thanks!

**Comment by bitwalker** [comment]
Extra settings in `config.*.exs` should be merged into the final configuration. I'll do some testing and figure out if we have a bug or if something weird is going on.

**Comment by bitwalker** [comment]
@mpahrens Configuration merging is happening as expected in my testing, but I think I know the issue here. I suspect `:blockytalky` in this case is not the name of an application present in your release, so when you run `Application.get_all_env(:blockytalky)` you would get `[]`, even if the setting is in `sys.config` in the release tarball. This is because the application has to be loaded in order for it's configuration to be made available. This is a restriction of releases. Can you confirm whether that's the case?

**Comment by mpahrens** [comment]
I'll take a look and see if those are the results I get as well. Sorry for the late response, took the weekend off. Working on it today and tomorrow.

**Comment by mpahrens** [comment]
side note, my extra settings (generated by the phoenix.new from 0.10 way back when) are named `prod.exs` and `dev.exs` and not prefixed with `config`. Is that an issue? Should they be renamed to something like `config.prod.exs` and `config.dev.exs`?

**Comment by bitwalker** [comment]
@mpahrens No that's fine, as long as they are imported in config.exs as expected.

**Comment by bitwalker** [comment]
@mpahrens ping :)

**Comment by mpahrens** [comment]
Yeah sorry for radio silence. I got moved projects temporarily. You can
close this issue test examples worked as you described so I think I'm all
set

**Comment by bitwalker** [comment]
@mpahrens Ok thanks!
