### ISSUE TITLE
Phoenix hot deployment static assets not using new version

### ISSUE THREAD

**Issue by midas** [bitwalker/exrm#206]
When using `exrm` to build releases for a Phoenix application (https://excasts.com), after the upgrade is complete, it seems that the static assets being used are  not the new set.   I am using Phoenix digesting in my application.

Paul, just a reminder from our conversation at ElixirConf, you theorized this may be related to the way Phoenix accomplishes its static asset serving. possibly their responsible server does not implement the `code_change` function.

Thanks and I look forward to working on this issue with you.

**Comment by keichan34** [comment]
In my application, I usually make an `asset_cache_bust/0` function:

```elixir
def asset_cache_bust do
  Phoenix.Config.clear_cache MyApp.Endpoint
  Phoenix.Endpoint.Adapter.warmup MyApp.Endpoint
end
```

Then, as part of the deploy script, I use a RPC to call it.

```
$ /mnt/app/bin/my_app rpc Elixir.MyApp asset_cache_bust
```

This is obviously a workaround that shouldn't be there, but it works for me. :smiley:

**Comment by bitwalker** [comment]
@midas I think I may have found the problem, in Phoenix's `config/config.exs`, the following configuration is present:

```elixir
config :my_app, MyApp.Endpoint,
  ...
  root: Path.expand("..", __DIR__),
  ...
```

The problem here is that `root` ends up expanding to an absolute path to the project directory when the release is built, so even when you do an upgrade, it's still pointing to the assets via that absolute path.

I overrode it in my example chat app I used in my talk at ElixirConf, by putting the following in `config/prod.exs`:

```elixir
config :chat, Chat.Endpoint,
  ...
  root: ".",
  ...
```

I then tested a style change with a rolling upgrade, and it worked exactly as expected. On the plane home I tried playing around with that setting a bit to try and find something that would work both with releases and without, but couldn't come up with a simple solution. I'm also not 100% sure that this was the problem you had (because the "bug" I found is dependent on an absolute path in the config), but depending on your deployment setup, it's entirely possible this was the culprit.

/cc @chrismccord

**Comment by chrismccord** [comment]
Would dropping a comment above the config that mentions root for releases be enough? We do similar comments for prod config around starting the web server.

**Comment by midas** [comment]
@bitwalker That seems plausible to me.  Will test on my end.  @chrismccord Want me to send a pull request for this comment addition?  I would love to get my first contribution in place.

Thanks gentlemen!

**Comment by chrismccord** [comment]
@midas Please do!

**Comment by midas** [comment]
@bitwalker Can you expand on the reason why this solution works so that I can explain a little more in depth?

**Comment by bitwalker** [comment]
@midas Sure! The reason it works is because when the configured path is read in the release, it will be done so relative to the application directory in the release (the currently installed version that is). So since the current working directory is already the desired directory for `root`, we can just set it to `.`.

**Comment by midas** [comment]
@chrismccord What effect will a root path of `.` have on the development environment?  Should this setting be overridden only in environments that will be built into a release, ie. production? 

Thus, do you think this comment should be in `config/config.exs` or `config/prod.exs`?

**Comment by bitwalker** [comment]
It should go in `prod.exs`, and the problem with just making the default `.` is that with mix it only works when running the project from the project root directory, if you are running an umbrella project or the current working directory is not the project root, it will be incorrect, which I assume is why the default is what it is today, but @chrismccord would have to chime in on that bit. I think by documenting that `root` needs to be configured when using releases in `prod.exs`, we can at least make sure nobody else gets bit by this. It would be nice if there was a more general solution so that `root` needn't be configured at all though.

**Comment by bitwalker** [comment]
@midas Is this resolved on the exrm side from your point of view? Can I close this for the time being?

**Comment by midas** [comment]
I think so.  Thanks again!

**Comment by midas** [comment]
@bitwalker, @chrismccord I have finally figured out what is causing this intermittent issue.  For the assets to update, there has to be a call to `config_change` of the `Endpoint`.  If there are no changes to the config, `config_change` appears to not be called.  Thus, the location of the new assets is not updated in the endpoint.  The way I am currently working around this is to add this to my `lib/config.exs`:

    config :my_app, MyApp.Endpoint,
      version: Mix.Project.config[:version]

This ensures that every release will have an update to the configuration without creating multiple places to update the version number.

I would like to update Exrm and Phoenix documentation and/or source code comments to reflect this if: 

1. It is an acceptable solution in your opinions
1. We can work together and agree on where/what updates should occur

Looking forward to your thoughts.

**Comment by chrismccord** [comment]
@midas I don't see anything wrong with this solution so 👍 from me on adding it to the phoenix deployment guide unless @bitwalker sees issues

**Comment by chrismccord** [comment]
@midas where did you find this configuration? I actually can't find in the code where we used it :)

**Comment by midas** [comment]
@chrismccord I did not find the configuration anywhere.  I worked with it in one of my private projects until I figured out the issue.  I can extract it into a public project so you can see it there.  Let me know if you would like for me to proceed with this solution.  Thanks!

**Comment by bitwalker** [comment]
Seems fine to me. Is there a particular reason why `config_change` is only called when the config changes, beyond the general idea of "don't do work you don't have to"? If there is no particularly significant cost to revaluation of the config every time, that would solve the issue without requiring users to see this workaround in the docs.

**Comment by midas** [comment]
@bitwalker, @chrismccord I am not sure how you need for me to proceed here.  Do you need an example project .  are we just discussing stuff?  Is anything needed form me?

Thanks!

**Comment by bitwalker** [comment]
@midas I'd say at the moment documenting the workaround you found is the first priority, but I still would like to discuss my last question as a more permanent solution, assuming there aren't issues with it.

**Comment by joshuaswilcox** [comment]
Adding `version` to my releases did not seem to fix this issue for me
My config.exs
```
# Configures the endpoint
config :scotchy, Scotchy.Endpoint,
  url: [host: "localhost"],
  root: ".",
  version: Mix.Project.config[:version],
  ...
```
and my prod.exs
```
config :scotchy, Scotchy.Endpoint,
  http: [port: 4444],
  url: [host: "beta.myurl.com"],
  debug_errors: true,
  root: ".",
  cache_static_manifest: "priv/static/manifest.json",
  server: true
```

**Comment by joshuaswilcox** [comment]
Nevermind.... I forgot to run `MIX_ENV=prod mix phoenix.digest` :/
