### ISSUE TITLE
Missing .conf file should generate default sys.config

### ISSUE THREAD

**Issue by eproxus** [bitwalker/exrm#209]
If no `myapp.conf` exists, starting the release produces an error.

Steps to reproduce

1. Create an app with a `.schema.exs` file but no `.conf` file.
2. Generate a release (which is generated succesfully.
3. Try to start the release. The following error is generated:

   ```
   Using myapp/rel/myapp/releases/0.0.9/myapp.sh
   myapp/rel/myapp/releases/0.0.9/myapp.conf not found in myapp/rel/myapp/releases/0.0.9
   ```

It would be nice if a default `sys.config` config is generated from the application defaults (or the schema). If the application contains enough sensible defaults in its `config/config.exs` file the release can actually be started without a `.conf` file.

That way, a `.conf` is optional and can override the default app configuration from `sys.config`.

Would it be possible to change the `generate_config()` function in https://github.com/bitwalker/exrm/blob/master/priv/rel/files/boot#L91 to do this?

**Comment by bitwalker** [comment]
@eproxus There is no point in a `.schema.exs` without the `.conf` though, this is an error that I would expect to be produced. You can simply `touch myapp.conf` and an empty file is sufficient to at least say "use all defaults", but I *do* want an error if someone attempts to boot a release with a schema but no conf, because the likely reason no conf exists is because of misconfiguration or accidental deletion, we don't want to boot the release as if nothing is wrong in that case.

**Comment by eproxus** [comment]
Okay, I can see that point. Going with an empty configuration for now.
