### ISSUE TITLE
Configuring logging in a release

### ISSUE THREAD

**Issue by midas** [bitwalker/exrm#221]
Currently releases include logging by default to the log directory.  It appears that the logging facility allows a file to grow to just under 1 MB and then continues logging in another file.  The names of the files are like `log/erlang.log.1`.  After 6 files, the log rotation starts over at 1.  This is surprising and problematic.

As we spoke of at ElixirConf, I checked out the configuration options of relx and saw nothing about the logging, excluding the [log level](https://github.com/erlware/relx/wiki/overlays#available-variables).

Either finding a way to configure or simply turning off this log output would be sufficient.  Any suggestions?

Thanks!

**Comment by bitwalker** [comment]
@midas Take a look [here](http://www.erlang.org/doc/man/run_erl.html). It appears that these logs cannot be disabled, but the number of logs, and their size, can be configured via environment variables. Does that help?

**Comment by midas** [comment]
The environment variables are exactly what I need.  Thanks!

Regarding the log level, it is currently outputting at debug which is not good.  Do you suggest the overlay path to fix this or another?  If the overlay path, then please expand a little on exactly how this should be accomplished.

Thanks!

**Comment by bitwalker** [comment]
@midas The relx log level is just for the tooling when building a release, it doesn't actually affect the logging of the release at all. The logs produced by `run_erl` are not configurable in their verbosity from what I can tell (unfortunately).

**Comment by midas** [comment]
Do you believe if we set the file size and max files for the run_erl logging to something small and then use the normal log configuration facilities of elixir we are introducing a performance inefficiency (that matters)?  It seems to me that depending on Elixir logging facilities plus something like logrotate is a better solution, considering the deficiencies in the run_erl log config.

**Comment by bitwalker** [comment]
@midas If you log to a file via Elixir's `Logger` module, instead of the console, very little output would be sent to the `run_erl` logs, so there should be no inefficiency there. You'd want to make sure you have `Logger` handle SASL reports as well though, because those will be sent to the `run_erl` logs by default.

**Comment by midas** [comment]
Thanks for your input, I will include all of this in my episode(s) on [ExCasts](https://excasts.com), which are already in production BTW.  Hopefully this will keep the same questions from being asked of you again.

**Comment by midas** [comment]
@bitwalker Any idea how I can verify that the SASL reports are making it to the log.  Is there a way to force one?  Thanks!

**Comment by bitwalker** [comment]
@midas In your `Logger` config, just make sure the following settings are there:

```elixir
config :logger,
  handle_sasl_reports: true,
  handle_otp_reports: true
```

Assuming you've got a file backend, that will make sure that all `sasl` and other Erlang system errors are in the same log.

**Comment by benwilson512** [comment]
Just wanted to pop in and mention that this issue has some really valuable info that I think ought to be mentioned in the documentation somewhere. Specifically the link to the run_erl config stuff, along with mentioning the sasl / otp logger settings.

**Comment by igalic** [comment]
it would be even more awesome, if we could (also) configure a remote (network) service as receiver of logs, not just a directory… but that might be a deeper erlang issue…

**Comment by eliast** [comment]
I just want to echo @benwilson512 

I shipped a phoenix project to production using edeliver/distillery and was seeing 7 to 9 second response times in requests and it took me days to figure out. I finally figure out how to do some fprof and found that most of the time was being spent by the logger. I guess it was rolling through files so fast that it was blocking on some notify function. I disabled all logging and everything worked. Then I found this post of course. 

Just sharing the experience here because just creating a project, fighting through deployment configuration and then you hit that bottleneck sucks. I'm not sure how else will people find this when using releases like exrm or distillery.
