### ISSUE TITLE
Forked relx scripts

### ISSUE THREAD

**Issue by tsloughter** [bitwalker/exrm#241]
I was wondering why some scripts from relx are forked and modified. Like https://github.com/bitwalker/exrm/commit/9d0e53878bf73b82e60121c986a5a4af1903a890 could have been merged into relx. Instead we both have different fixes for the same bug.

We should really be sharing scripts like this not only to dedup work we have to do but also so users of both relx and exrm benefit from improvements.

**Comment by bitwalker** [comment]
@tsloughter That commit in particular I'd gladly revert, since there's really no point in having a forked version of it. If I recall I did that one in a bit of a hurry, which is why I forked it instead of upstreaming it.

In general I absolutely agree, however I've had to keep the boot scripts forked because of the modifications I made to use an Elixir shell vs Erlang one, and to add in the hooks for conform. If there was a good way to add support for those things from within relx itself, I'd gladly work on that, but I'm not sure what that approach would be. If you have thoughts though, I'm open.

My intention with the forked scripts has been to merge changes from relx into the forked versions exrm uses, but it's difficult because the changes I've made since forking have been quite extensive, so fixes are often a translation instead of a straight merge, and I've fallen behind.

What I'd really like to do is have a modular boot script which permits users to set which shell (Elixir, Erlang, or something else) `console/remote_console/attach` will use, and provides a way to hook extensions into it (for things like conform). I'm decent at sh, but I'm lacking the know-how to write a script like that, assuming it's possible, at least not without some research.

**Comment by tsloughter** [comment]
Cool, no need to revert, just wanted to find out what happened.

And yes, I agree about the boot script. The more modular or easily replaced boot script is something I -- or @joedevivo :) -- have to figure out to integrate cuttlefish support into relx. So hopefully we'll have something to make that possible in the not to distant future.

Feel free to close this now, you weren't on irc so I couldn't just ping you there about it. Or leave it open as a place to discuss the modular boot script functionality.

**Comment by bitwalker** [comment]
@tsloughter I'll close this for now, but keep me posted on where you guys go with the boot script, if you want to talk through it sometime, just ping me on IRC or shoot me an email (it's in my GitHub profile).
