### ISSUE TITLE
Released app crashes when @on_load hook is used

### ISSUE THREAD

**Issue by pb82** [bitwalker/exrm#244]
Hi,

it seems there is a problem with releases when modules use the `@on_load` hook. I use it in a module to call `:crypto.rand_seed`.

- When i start the app with `iex -S mix` everything works as expected
- When i build a release and run `rel/app/bin/app console` it crashes as soon as that module is loaded.

The error message is:
```erlang
{"Kernel pid terminated",application_controller,"{application_start_failure,testapp,{bad_return 
{{'Elixir.Testapp',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Testapp',start,[normal,[]],[]} 
{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
```

I created a minimal example that demonstrates this bug (?), you can find it here:
https://github.com/pb82/ex_release_crash

I should add that this only happens if i actually do something in `@on_load` (tried several function from `:erlang`and `:crypto`, always crashed). When i just return `:ok` the error does not occur.

Any ideas?
Thanks!

**Comment by bitwalker** [comment]
I tested with the following in the `seed/0` function:

```elixir
IO.puts(IO.ANSI.yellow <> "seed" <> IO.ANSI.reset)
:erlang.timestamp()
:ok
```

And it worked as expected. One problem I thought would be the root issue is that you didn't have `:crypto ` and `:ssl` in your applications list in `mix.exs`, however it appears the problem is due to the fact that `:crypto` itself has an `on_load` attribute set, and I think your `on_load` is being called before crypto's, which is resulting in `:crypto` functions appearing to not be defined. Releases run in embedded mode, and according to Erlang's documentation, when running in embedded mode, first all modules are loaded, and then all of the `on_load` functions are called. However, if an on_load function calls a function in a module with it's own `on_load` which hasn't yet been executed, it will be unable to complete, hence the `undef` error in the stacktrace.

According to the Erlang docs, `on_load` is still very experimental, and issues like this can occur. Do you have a specific reason you need to make use of `@on_load` instead of some other mechanism? It should also be noted that `on_load` is called anytime the module is loaded, and this includes compilation, which may be undesired depending on what you are doing there.

**Comment by pb82** [comment]
You are right, after I add `:crypto` to the applications list it works. I don't have a specific requirement for `@on_load` I just thought it would be a convenient place to put initialization code. But thanks for pointing out the gotchas!

Since this was a mistake on my side i think we can close the issue?

**Comment by bitwalker** [comment]
Sure :)
