### ISSUE TITLE
New releases don't use new versions of static assets

### ISSUE THREAD

**Issue by koolhazcker** [bitwalker/exrm#253]
The path to the css file in my releases doesn’t change, i.e. it still points at some old css. I’ve tried the solution to #206 but it didn’t work -- I must have done something else wrong.

**Comment by sircharleswatson** [comment]
I'm having the same issue with the JS file

**Comment by daisuke-morita** [comment]
I encountered the same issue. In my case, it appears that just changing any value of `config :my_app, MyApp.Endpoint` will update the assets paths to the new version.

For example, if I try the solution in #206 (root: ".",) and upgrade my app, it will update the paths only for that upgrade. After that, when I upgrade it again, the urls remain the old version.

As a workaround, I added a config value `my_app.Elixir.MyApp.Endpoint.version` and change it every time when upgrading, and it works.

**Comment by bitwalker** [comment]
@daisuke-morita @sircharleswatson @koolhazcker Looks like this is due to the fact that Erlang's config_change callback doesn't consider the `:root` config value to have changed (it's "." in both versions). If no other config values change, the configuration isn't updated.

@chrismccord It seems (from the documentation) that `:root` is only intended for use with code reloading enabled, but I'm also struggling to find a solution whereby one can make sure the assets path is always updated during an upgrade. Do you have any suggestions? Seems like ultimately, the source of the problem is that a path to the application root has to be provided. What if instead of providing a path, one provided their application name (which could be gotten from Mix.Project as part of templating a new project), and then use `Path.join("#{:code.priv_dir(:app_name_from_config)}", "..")` to get the root path of the application. I know there isn't any great solution to this, but that seems more resilient to changes of environment or deployment strategy than a static path.
