### ISSUE TITLE
App not compiled when release with MIX_ENV=prod

### ISSUE THREAD

**Issue by ThijsWouters** [bitwalker/exrm#256]
My phoenix app is not compiled when I release with `MIX_ENV=prod`.

This builds the release:
-  `rm -rf _build`
- `mix release`

This does not:
-  `rm -rf _build`
- `MIX_ENV=prod mix release`

This compile all dependencies, but does not compile my app.

This does build a release:
-  `rm -rf _build`
- `MIX_ENV=prod mix compile`
- `MIX_ENV=prod mix release`

**Comment by antipax** [comment]
Yeah, I was having the issue. The when I ran with --verbosity=verbose, the app_discover provider failed and the error said it couldn't resolve my app, which is presumably because it was unbuilt.

**Comment by bitwalker** [comment]
Yes, you have to compile before you can run the mix release task, however I've pushed a change to master so that the compile task is explicitly run before the release task runs, so this should no longer be an issue. You still have to compile after fetching deps with exrm the first time in order to access the release task, but that's expected.
