### ISSUE TITLE
Any way to skip the check if a particular application is included?

### ISSUE THREAD

**Issue by alco** [bitwalker/exrm#258]
I have a project with a bunch of dev-only and test-only dependencies. When I run `mix release`, it shows a warning that some applications are not included in the list of `:applications` and waits for a confirmation to proceed.

I know there's a `--no-confirm-missing` flag, but I'm looking for a way to mark individual deps as excluded from the release so that exrm doesn't complain about them. Ideally I would like to run `mix release` without the `--no-confirm-missing` flag on CI. That way, if I add any dependency in the future and forget to include it in the release, I will want `exrm` to complain and the CI run to fail. However, that can only be achieved if there's a way to exclude certain dependencies that I specifically don't want to include in the release.

**Comment by MSch** [comment]
In our case those are Erlang dependencies that depend on `edown` to build but not to run, since they're still on rebar 2 / erlang.mk which don't support the concept of dev-only deps.

**Comment by bitwalker** [comment]
If you run your release build with `MIX_ENV=prod`, but have those deps in your mix.exs marked with `only: [:dev, :test]` or whatever, then exrm should not be warning for any of those dependencies, or their transitive dependencies. Is that not the case? Or are you talking about running a release build with `MIX_ENV=dev` for example, where it's not possible to distinguish between prod and development deps?

**Comment by MSch** [comment]
@bitwalker in that case the erlang project can't be compiled, because it depends on e.g. `edown` during compilation.

**Comment by bitwalker** [comment]
@MSch I see, makes sense! Let me try something and get back to you.

**Comment by bitwalker** [comment]
@MSch I just pushed a change to master which I think should solve this neatly. With the change I made, add `warn_missing: false` to the dep you want to ignore, i.e.:

```elixir
def deps do
  [{:timex, ">= 0.0.0", warn_missing: false}, ...]
end
```

This will cause that dependency, and any of it's transitive dependencies to be skipped as part of the check for missing applications. Mind giving it a shot?

**Comment by MSch** [comment]
@bitwalker This works, but only for dependencies that are listed in `deps`. Conceptually I would have thought adding a list `skipped_applications` or `ignored_applications` would make more sense, considering that there's already `applications` and `included_applications`.

```elixir
  def application do
    [
      applications: [
        :logger_file_backend, :logger, :lager, :lager_logger,
        :setup, :exometer, :dogstatsd,
        :sasl, :syntax_tools, :compiler,
        :backoff, :connection,
        :gproc, :sidetask, :poolboy, :sbroker,
        :crypto, :comeonin, :hashids,
        :exjsx, :timex,
        :postgrex, :ecto,
        :ranch, :cowboy, :plug, :gun,
        :zbase32,
      ],
      included_applications: [:dbg, :eper, :recon],
      skipped_applications: [:edown, :parse_trans]
    ]
  end
```

**Comment by bitwalker** [comment]
The reason why I don't like something along the lines of `skipped_applications` is because the warning presented actually isn't about the applications per se, but more specifically about dependencies which contain applications which haven't been explicitly added to the release (via `applications` or `included_applications`). By making the flag for disabling the warning an option on the dependency, it maps much more cleanly to the use case for the warning in the first place: You've added a dependency, and either forgot to add it to applications/included_applications, which is what you want to be warned about, *or*, you added a dependency and don't want to ever be warned about it because you know the warning is spurious or irrelevant for whatever reason, in which case, you want to ignore not the application being warned about, but the dependency generating the warning, because it's likely that the dependency itself might have transitive dependencies which themselves may generate warnings.

For your example use case, it seems to me that it makes sense to bring `edown` into your `mix.exs` as an explicit dependency, and add `warn_missing: true`.

I'm open to being swayed on this of course, but right now it just feels wrong adding another `*_applications` setting in mix.exs, when the issue being solved is that people aren't using the settings that exist properly in the first place due to confusion about them.

**Comment by MSch** [comment]
Ah, I didn't know it was on the dependency not on the application level. I also didn't know that hex/mix allowed adding arbitrary keys to a dependency, but that's the only other argument against `warn_missing` I have.

**Comment by bitwalker** [comment]
Dependencies in `mix.exs` are supposed to be abstracted from their specific fetching mechanism, so in theory you could have an FTP fetcher, etc. In order to support the varying options any given fetcher might have, options provided in the dependency tuple are just stored in the `:opts` key of the `Mix.Dep` struct, so they are available to anyone really. So we can add anything dependency specific there without worrying about breaking things, though we do have to be careful with our naming to prevent accidentally clobbering valid options with values that are intended to mean something else. In this case, there is no `warn_missing` option for any of the native Mix dependency fetchers, but perhaps the name could be changed if people feel like there is a better choice.
