### ISSUE TITLE
Remote consoles only seem to work once

### ISSUE THREAD

**Issue by pragdave** [bitwalker/exrm#267]
First, thanks for exrm. It is a joy to use.

I'm writing a section on using it for a new version of _Programming Elixir_. To demonstrate deploys, I'm ssh-ing back to my local machine.

However, `remote_console` only starts once:

~~~ elixir
[~] ssh localhost deploy/bin/sequence start
Using /Users/dave/deploy/releases/0.0.1/sequence.sh

[~] ssh localhost deploy/bin/sequence remote_console
Using /Users/dave/deploy/releases/0.0.1/sequence.sh
Interactive Elixir (1.2.0-rc.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(remsh-sequence@127.0.0.1)1> ^C  Killed by signal 2.

[~] ssh localhost deploy/bin/sequence remote_console
Using /Users/dave/deploy/releases/0.0.1/sequence.sh
{error_logger,{{2015,12,31},{13,58,40}},"Protocol: ~tp: the name remsh-sequence@127.0.0.1 seems to be in use by another Erlang node",["inet_tcp"]}
~~~

What am I doing wrong?

Cheers

Dave

**Comment by bitwalker** [comment]
It looks to me like you are killing the ssh session, but not the remote console session, so the next time you ssh in and run `remote_console` it's trying to start another instance of the console, but it's starting up with the same node name (hence the error). While we could probably generate a random id for the remsh node, I think it's probably a bad idea because you wouldn't realize that you are starting new nodes each time without killing them when you're done.

**Comment by pragdave** [comment]
I agree. But I can't work out how to kill the remote. ^Gq just gets echoed
back.

But, thinking about it, this isn't an exrm issue (unless there's some magic
you can do), so feel free to close this.

Thanks again


Dave

On Thu, Dec 31, 2015 at 2:07 PM, Paul Schoenfelder <notifications@github.com

**Comment by bitwalker** [comment]
@pragdave Doing some brief research, I think you want to run `ssh -t localhost deploy/bin/sequence remote_console`, this will pass through `^C` to the session on the remote side, which should behave the way you want. Without that, it runs non-interactively and your local ssh session gets sent the SIGINT signal.
