### ISSUE TITLE
`check_install_release failed` when upgrading

### ISSUE THREAD

**Issue by arnvald** [bitwalker/exrm#279]
Hi @bitwalker,

thanks for your project, I've been trying it out for the last couple days and it looks very promising. I managed to deploy my application very easily.

I've had a few problems though when performing an upgrade. The last one is quite surprising. Basically it seems that the new release does not get unpacked.

I'm running it exactly as in upgrade documentation, and here's the result I get:

```
Using /home/deploy/apps/my_app/releases/0.0.1/my_app.sh
Release 0.0.2 is already unpacked, now installing.
Generating vm.args/sys.config for upgrade...
cp: cannot stat ‘/home/deploy/apps/my_app/releases/0.0.2/sys.config’: No such file or directory
sys.config ready!
cp: cannot stat ‘/home/deploy/apps/my_app/releases/0.0.2/vm.args’: No such file or directory
vm.args ready!
Release 0.0.2 is already unpacked, now installing.
ERROR: release_handler:check_install_release failed: {no_such_file,
                                                      "/home/deploy/apps/my_app/releases/0.0.2/start.boot"}
```

When I enter the `releases/0.0.2` directory, I see there only `my_app.tar.gz` and `vm.args` files.

I'll try to provide a sample app that reproduces this issue later today, but if anyone already knows why this might be happening, I'll be grateful for any help.

I'm using Elixir 1.2.0 on Erlang/OTP18 with Exrm 1.0.0-rc7

**Comment by arnvald** [comment]
It seems that I caused the problem by messing with releases numbers. At some point I couldn't make upgrade working and I decided to remove all the releases and go back to 0.0.1
I removed all the directories, but then running `bin/my_app upgrade 1000.0.0` showed that release `0.0.2` already exists and is unpacked, even though I had removed all the directories.

So I think my issue is reduced to a question - where are the information about releases stored except for `rel` directory in the main repo and `releases` in the build dir?

**Comment by bitwalker** [comment]
@arnvald Sorry for the long delay :(

The file which tracks which releases are installed is `releases/RELEASES`, and `releases/start_erl.data` tracks the current release version and ERTS version. I would recommend that if you are going to start from scratch with a release that you blow away the entire deploy directory, but that's not strictly necessary - just safest. There are some caveats around versioning and building release upgrades.

- Versions must be greater than the last version (i.e. 0.0.1 -> 0.0.2)
- Upgrades which are built against a specific version, this is significant because if for example you are building a release for 0.0.4 and the last release on your build machine was 0.0.2, but the current deployed version is 0.0.3 because someone else built the last upgrade package, means that you can't install 0.0.4 without first downgrading to 0.0.2 and then upgrading to 0.0.4. This is because the relup instructions which tell your application how to upgrade itself are specific to the code in the version it's built against.
- If you want to build upgrades, you have to have the last release around, if you blow away the rel directory on your build machine, it won't be possible to build an upgrade anymore (you'd have to deply the new version of the app with a full restart, and build upgrades starting from that release).

This should all be in the documentation, but just as a quick recap of the key points :)
