### ISSUE TITLE
Optionally exclude elixir distribution for pure-erlang projects

### ISSUE THREAD

**Issue by sanmiguel** [bitwalker/exrm#31]
I'd love to be able to build purely erlang projects using `mix` and `exrm`. A stepping stone to this is being able to configure a release to exclude the elixir/iex runtime.

Example project with first steps to a working `mix.exs` for compiling and building release here: https://github.com/sanmiguel/rest_service/tree/r17-maps-mix

**Comment by bitwalker** [comment]
I'm closing this for now, since I feel that relx is a better choice for pure-Erlang projects. Not only is relx available on hex now, but wrapping it with a simple mix task (for an Erlang project) is very trivial, while refactoring exrm to work well for both Elixir and Erlang projects is not. Should there be more demand for this, I'll gladly revisit, but I haven't heard any other requests for this capability.

**Comment by sanmiguel** [comment]
:+1: This is no longer really necessary.
