### ISSUE TITLE
Cannot get application to start from exrm release

### ISSUE THREAD

**Issue by mylanconnolly** [bitwalker/exrm#318]
Hey all,

I am attempting to get exrm to work on my application. I found that when I build the application on the server and run the exrm release from it, it works fine.

When I try to build on my laptop and deploy the exrm release to the server, it does not.

Both my laptop and server have the same Elixir and Erlang versions (installed using [asdf](https://github.com/HashNuke/asdf/)... they are 1.2.3 and 18.2.1 respectively).

My build script is like this:

```shell
#!/bin/bash

export MIX_ENV="prod"

exists() {
  command -v "$1" >/dev/null 2>&1
}

if ! exists erlc; then
  echo "Erlang doesn't seem to be in \$PATH!"
  exit 1
fi

if ! exists elixirc; then
  echo "Elixir doesn't seem to be in \$PATH!"
  exit 1
fi

if ! exists mix; then
  echo "The mix command doesn't seem to be in \$PATH!"
  exit 1
fi

if ! exists npm; then
  echo "The npm command doesn't seem to be in \$PATH!"
  exit 1
fi

echo ">>> Removing old artifacts..."
rm -rf _build
rm -rf deps
rm -rf priv/static
rm -rf node_modules

echo ">>> (Re)installing dependencies..."
mix deps.get
npm install

echo ">>> (Re)compiling project..."
mix compile
brunch build --production
mix phoenix.digest
mix release --dev --verbosity=verbose
```

My release script is like this:

```shell
#!/bin/bash

rsync -rvzh --info=progress2 rel/minerva "$1":/srv
```

I am using rsync because I was running into an issue where I could not package into a tar (I had to pass `--dev`, which works fine).

When I run the exrm release built from my laptop, I get the following:

```shell
$ bin/minerva console                       
Using /srv/minerva/releases/0.1.0/minerva.sh
Exec: /srv/minerva/erts-7.2.1/bin/erlexec -boot /srv/minerva/releases/0.1.0/minerva -boot_var ERTS_LIB_DIR /srv/minerva/erts-7.2.1/../lib -env ERL_LIBS /srv/minerva/lib -config /srv/minerva/running-config/sys.config -pa /srv/minerva/lib/minerva-0.1.0/consolidated -args_file /srv/minerva/running-config/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /srv/minerva
/srv/minerva
{"init terminating in do_boot",{'cannot load',error_handler,get_files}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
```

My `rel` directory was empty, as I suspected it might have been dirty from a previous build or something, so I deleted it and built it again. This would be an initial release so I don't care about upgrades yet.

Anyone have an idea of what's going wrong?

Thanks!

**Comment by mylanconnolly** [comment]
Nevermind, I goofed.

My rsync command was wrong. For future reference, the rsync command was omitting the symbolic links of dependencies, causing the error.

**Comment by bitwalker** [comment]
Hey sorry I wasn't able to get to this, but you got it figured out anyway :)

Could you elaborate on the issue with generating the tarball? I don't think you'll want to deploy with `--dev`, I mean, seems like it works, but I'd rather figure out the root cause in case it's a bug in exrm/relx.

Also, the use of `{include_erts, false}.` is one of the "cross-compilation" strategies for building releases on one OS and deploying to another - another option is to pull the Erlang lib directory from your prod machine (or one with the same OS and versions of OpenSSL), and use `{include_erts, "path/to/erlang/lib"}.`, which will then bundle the ERTS specified by the path. The reason you need to do this is because Erlang is dynamically linked to some system libraries, and contains some natively implemented functions built for the specific architecture it was installed on. This is covered in more detail in the docs, but just in case you were wondering what it does (and what your options are).

Thanks for the kind words! I'm always happy to hear success stories :)

**Comment by mylanconnolly** [comment]
Thanks for the reply!

The issue I was coming across seems to be the one noted in #264 and #299. All the symptoms seem identical and some of my module names are fairly long. I *could* rename some of the modules, but it will likely take a while, since I have a lot of other things going on at the same time. Just out of curiosity, what are the implications of `--dev`? I saw some information, but I don't have a 100% solid grasp on that.

Thanks for the explanation on the `{include_erts, false}.` bit. I suspected as much was going on, however I definitely appreciate the thorough information (as well as alternative options).
