### ISSUE TITLE
mix release on mac doesn't run on linux

### ISSUE THREAD

**Issue by arielze** [bitwalker/exrm#35]
Hi,
I've build the project on my mac running 'mix release', I copied the tar.gz file into our test server on Amazon, running linux 14.04.
While trying to run it I get this message:
erts-6.0/bin/escript: 1: erts-6.0/bin/escript: Syntax error: "(" unexpected
We used this server previously to run the project successfully, build on linux running 'mix release'.

Please advice,
Ariel

**Comment by localshred** [comment]
Hi @bitwalker,

I'm running into this same issue, compiling from OSX 10.11.12 and trying to run on ubuntu 14.04.2. Above you stated:

> It's not currently possible to cross-compile releases between OSX and Ubuntu.

Is this still the case? Is there anything you can point me towards to move forward? I can build on linux if necessary but I'd like to avoid setting up a build machine if at all possible. Thanks for the awesome lib!

**Comment by localshred** [comment]
Oh, and since you'll ask:

+ Erlang/OTP 18 [erts-7.2.1]
+ Elixir 1.2.0
+ exrm 1.0.0-rc7
+ conform_exrm 0.2.0
+ conform 1.0.0-rc8

**Comment by localshred** [comment]
And the error I encountered, similar to the one in this issue:

```
/app/gretel/current/bin/gretel upgrade 0.0.1
/app/gretel/current/erts-7.2.1/bin/escript: 1: /app/gretel/current/erts-7.2.1/bin/escript: Syntax error: ")" unexpected
Using /app/gretel/current/releases/0.0.1/gretel.sh
Node is not running!
  ERROR: Command Failed
/app/gretel/current/erts-7.2.1/bin/escript: 1: /app/gretel/current/erts-7.2.1/bin/escript: Syntax error: ")" unexpected
```

**Comment by bitwalker** [comment]
@localshred Yes this thread is pretty seriously outdated, the following instructions for cross-compiling your release are something I posted in a similar thread [here](https://github.com/phoenixframework/phoenix_guides/issues/254):

---
See the solution in bitwalker/exrm#163, basically the steps are as follows:

- Add exrm to your project
- `$ mkdir -p rel && vim rel/relx.config`
- Add `{include_erts, <path to lib/erlang>}.`
- Run `mix release`

So for example, on my OSX machine, I have Erlang 17.5 installed with Homebrew, and the path I would add to `relx.config` to use it is: `/usr/local/Cellar/erlang/17.5/lib/erlang`. You can validate the path you are providing is correct because `$ ls <path>` should contain a folder named like `erts-X.X.

----

Follow those instructions and you should be good to go!

**Comment by localshred** [comment]
Ok good to hear. I'll check that out. Thanks!
