### ISSUE TITLE
vm.args is only copied from release once

### ISSUE THREAD

**Issue by aaronjensen** [bitwalker/exrm#360]
At the moment it seems that `vm.args` is (intentionally?) copied from the release directory to `running-config` only the first time. After that, it is no longer copied regardless of whether or not you upgrade, switch to a new version, etc. This is a surprising behavior because conform config copies every time boot is run (which actually [wasn't the case](https://github.com/bitwalker/exrm/pull/283)). Should we treat vm.args the same way?

**Comment by bitwalker** [comment]
Yes, vm.args should be treated the same way. We'll need to make sure the boot script does that.

**Comment by bitwalker** [comment]
Per our conversation on IRC, here's my findings/suggested fix for this in exrm:

- Currently, sys.config in `running-config` is always overwritten when `generate_config` is called. This is not how I want `running-config` to operate. This isn't an issue with conform, as config changes are made in the .conf. We want `running-config` to be persistent so that custom configuration can be done there.
- vm.args in `running-config` is only created the first time, and other than deleting it, there's no way to get the vm.args from the release package there. The persistence is desired, but there needs to be an escape hatch.

My suggested/planned fix for this: Define a new environment variable `PERSISTENT_RUNNING_CONFIG`. When set, sys.config and vm.args in `running-config` will never be overwritten with versions in the release package, with the exception of when using conform, where sys.config will still be overwritten. When unset, sys.config and vm.args will always be overwritten by their counterparts in the release package (basically the current behaviour, except vm.args will also be overwritten after this change).

Any feedback on this proposed change is welcome from all :)
