### ISSUE TITLE
Log messages have iex prefix on started release

### ISSUE THREAD

**Issue by liveforeverx** [bitwalker/exrm#361]
Probably I need to switch to other logging, but default logging to file by start writing this before every message, which is little bit annoying, but probably is idea, that it works in this way?

Every log message have:

```elixir
iex(app@node)1>
```

By checking release script, I see: `START_OPTION="console"`

```bash
    start)
      shift
      START_OPTION="console"
      HEART_OPTION="start"
      ;;
```

**Comment by hamiltop** [comment]
Unfixed in https://github.com/bitwalker/exrm/commit/9184f2e890cdd2692d43024a153c14d4bb7f7eae

**Comment by bitwalker** [comment]
@hamiltop Attach does not work if the daemon is started with `foreground`, it has to be started with `console` unfortunately, so this is less of a regression, rather than a calculated tradeoff. If anyone has ideas on how to resolve both issues, I'm open, but `attach` is more important to me than removing the iex prompt from the log file.

**Comment by hamiltop** [comment]
Why is attach important? I can't think of a use case that remote_console
doesn't solve.

**Comment by bitwalker** [comment]
`remote_console` requires establishing a connection to the node, if for some reason the node is not responding to pings/remote connections, you can still get to a shell on the node with `attach`, because it just attaches the terminal to the pipe for the shell of the running node. In my opinion it's an important failsafe if you need to access a node to do troubleshooting in a situation like that. Obviously `remote_console` should be everyone's go-to for shelling into a node, but `attach` exists because it fills in a critical gap for introspection/surgery of a live system - if you can't remotely access the system, you'd be out of luck without `attach`.
