### ISSUE TITLE
Support releases on Windows

### ISSUE THREAD

**Issue by Scramblejams** [bitwalker/exrm#48]
relx doesn't, in its present state as used by exrm, seem to run on Windows. Therefore releases can't be produced on that platform.

**Comment by fire** [comment]
Is there any progress?

**Comment by zabirauf** [comment]
Any updated?

**Comment by fire** [comment]
It seems like many of the bugs in relx have been solved. Can you check if it's possible to support exrm on Windows now?

**Comment by bitwalker** [comment]
@fire Now that relx has been switched over to being included as a library rather than a raw binary this can proceed, the only task that really needs to be done is to modify the windows boot script the same way the shell script for other platforms was modified.

**Comment by fire** [comment]
Not familiar with the details of exrm, but I'm available to test the code on Windows.

**Comment by bitwalker** [comment]
This has been pushed in 0.18.1. I was testing on my Windows 10 dev machine, so I'll need you guys to test in your environments to make sure things are solid.

**Comment by fire** [comment]
A basic development test allows me to release a phoenix server on Windows 8.1 64bit and run it. 

There was issues with setting environmental variables. In particular the default phoenix code requires the ability to set PORT=XXXX and MIX_ENV=prod.

There was a workaround that allows me to switch to a user and apply env variables to that user, but it would be help to have some guidance.

**Comment by bitwalker** [comment]
@fire I would just write a simple batch script to bootstrap the phoenix reqs, something like this:

```batch
@echo off
set PORT=8080
set MIX_ENV=prod

.\path\to\bin\app.bat start
```

I can put a note in the exrm documentation if that seems like a reasonable solution.

**Comment by fire** [comment]
Doesn't this break .\path\to\bin\app.bat install, .\path\to\bin\app.bat start? The idea is you're able to install the service without creating your own service manually.

**Comment by bitwalker** [comment]
@fire You're right it does, I keep forgetting it installs as a service on Windows. The following are the steps that should work, and allow finer grained control (rather than creating a user for each service);

1. Post-install, create a new `REG_MULTI_SZ` value under the registry key `HKLM\SYSTEM\CurrentControlSet\Services\<YourAppsService>`
2. Add your environment variable definitions in the form of:
```
VAR1=VALUE1
VAR2=VALUE2
```

At that point, you should be able to start your service up, and the environment you just defined will be available to the service.

If you could verify that this works (I'm unfortunately too busy at the moment to test this myself), I'll add documentation to exrm around this process (potentially I could find a way to expose this as a friendlier/automatic thing that happens during installation/startup), for instance exposing something like env.conf, which is fed into something that updates the registry on startup.

**Comment by fire** [comment]
Your instructions are missing "Create a REG_MULTI_SZ called Environment.".

**Comment by fire** [comment]
1. Post-install, create a new REG_MULTI_SZ value named Environment under the registry key HKLM\SYSTEM\CurrentControlSet\Services\<YourAppsService>
2. Add your environment variable definitions in the form of:
VAR1=VALUE1
VAR2=VALUE2

Works
