### ISSUE TITLE
config.exs evaluated at release creation time

### ISSUE THREAD

**Issue by stocks29** [bitwalker/exrm#75]
I'm not sure if this is intended or not, but because config.exs is evaluated when the release is built, all System.get_env() calls inside config.exs are evaluated at the time the release is generated. Typically these calls are intended to be executed at runtime so the application can be dynamically configured at that point.

The downside is that sensitive properties (database passwords, etc...) are not able to be passed to the application configuration via an environment variable.

Is this intended? Many docs seem to imply that System.get_env() is perfectly fine in config.exs. Example:

    https://github.com/phoenixframework/phoenix
        \-> Configuration for SSL 

So yeah... this may be a bug, or it may just be me not understanding the right way to accomplish what I'm trying to do.

Thanks! :)

**Comment by NhanHo** [comment]
According to the other linked issue, one way to get around this would be using:

`System.get_env("PORT") || Application.get_env(:phoenix, :port) || 4000`

But in this case, isn't `Application.get_env/2` just getting the data from `mix.exs` rather than environment variable? Or am I missing something here?

**Comment by bitwalker** [comment]
@NhanHo The point here is that you first consult the environment via `System.get_env`, then fetch the configured value from `sys.config` via `Application.get_env/2`, then fall back to some safe constant. `Application.get_env/2` does not pull from `config.exs` here, because by the time this code is being executed, `config.exs` has been compiled to `sys.config`, where the values are static (i.e., if you have a `System.get_env` call in your `config.exs`, it would be whatever the return value of that was in the compilation environment when stored in `sys.config`.

**Comment by mm-tfx** [comment]
Hello, There is something I am missing probably but I cannot make it work.
I would like to configure my phoenix app. I am talking about release version since for development I made it this.
I would like to make it possible to configure the port by the user through env variable PORT.
When this variable is not defined then I would like to pass 0 to the app and hence application would itself select free port.
I tried this `System.get_env("PORT") || Application.get_env(:phoenix, :port) || 0`
I tried to modify schema following this article http://carlo-colombo.github.io/2016/05/04/The-3-E-Elixir-Exrm-and-Environment-Variables/
It works only if I would set this PORT variable prior to release creation. Otherwise app will get 0 and hence selects port by itself.

I'll keep searching but I would appreciate some tips. Thanks.
