### ISSUE TITLE
Generating upgrades from a fresh clone of repository

### ISSUE THREAD

**Issue by robotarmy** [bitwalker/exrm#85]
In-order to upgrade the software has to believe that it has more than one version active when it generates the release. 

Is it possible to tell exrm that there are releases without having generated the previous release?

It would possible to check 'rel' into the repository, which i believe will give exrm the ability to know that there have been prior releases as a work around.

Is the rel/releases directory a pre-condition for 'mix release' that will build an upgrade?

**Comment by hexedpackets** [comment]
What about when using an ephemeral build server, such as from CircleCI or TravisCI?

I use OS X for development but deploy to Ubuntu, so my local builds aren't usable. Having the build service compile the application works for the initial release but the server gets purged after the build. 

The only way I can see making the release upgradeable through the build service would be to have it commit those files back to the repo after building, which I'd like to avoid doing if at all possible.

**Comment by bitwalker** [comment]
Ultimately the only way you can build upgrades for an application is to have the prior release (basically the following directories/files:

- `rel/app/lib`
- `rel/app/releases/RELEASES`
- `rel/app/relup`
- `rel/app/releases/<upfrom version>`

If you aren't storing these files in source control, then you must use a non-ephemeral build server, because upgrades are stateful, and require that they have the previous version's binaries available for the relup/appup generation. Building releases can be done with an ephemeral build server no problem, but I don't consider hot upgrades to be compatible with that setup, unless you are willing to store the binary files in source control.
